// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2025-11-06T15:28:19.836Z

import type { FiletypeParserOptions } from "./types"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const asset = (rel: string) => resolve(__dirname, rel)

// Cached parsers to avoid re-resolving paths on every call
let _cachedParsers: FiletypeParserOptions[] | undefined

export function getParsers(): FiletypeParserOptions[] {
  if (!_cachedParsers) {
    _cachedParsers = [
      {
        filetype: "javascript",
        queries: {
          highlights: [asset("./assets/javascript/highlights.scm")],
        },
        wasm: asset("./assets/javascript/tree-sitter-javascript.wasm"),
      },
      {
        filetype: "typescript",
        queries: {
          highlights: [asset("./assets/typescript/highlights.scm")],
        },
        wasm: asset("./assets/typescript/tree-sitter-typescript.wasm"),
      },
      {
        filetype: "markdown",
        queries: {
          highlights: [asset("./assets/markdown/highlights.scm")],
          injections: [asset("./assets/markdown/injections.scm")],
        },
        wasm: asset("./assets/markdown/tree-sitter-markdown.wasm"),
        injectionMapping: {
          "nodeTypes": {
                    "inline": "markdown_inline",
                    "pipe_table_cell": "markdown_inline"
          },
          "infoStringMap": {
                    "javascript": "javascript",
                    "js": "javascript",
                    "typescript": "typescript",
                    "ts": "typescript",
                    "markdown": "markdown",
                    "md": "markdown"
          }
},
      },
      {
        filetype: "markdown_inline",
        queries: {
          highlights: [asset("./assets/markdown_inline/highlights.scm")],
        },
        wasm: asset("./assets/markdown_inline/tree-sitter-markdown_inline.wasm"),
      },
      {
        filetype: "zig",
        queries: {
          highlights: [asset("./assets/zig/highlights.scm")],
        },
        wasm: asset("./assets/zig/tree-sitter-zig.wasm"),
      },
    ]
  }
  return _cachedParsers
}
